on:
  push:
    branches:
      - "master"

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz
          - target: x86_64-unknown-linux-musl
            archive: tar.xz
          - target: x86_64-unknown-linux-musl
            archive: tar.zst
          - target: x86_64-apple-darwin
            archive: zip

    steps:
      - uses: actions/checkout@v3
      
      # Step to compile the Rust project
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}

      # Upload compiled binaries
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}-${{ matrix.archive }}
          path: ./target/${{ matrix.target }}/release/*${{ matrix.archive }}

  publish-release:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.target }}-${{ matrix.archive }}
          path: ./artifacts

      # Create GitHub release and upload the artifacts
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./artifacts/*
